Fix issue with getting all team outcomes
```
  File "/usr/local/lib/python3.6/site-packages/tpg/tpg_trainer.py", line 169, in evolve
    self.select(fitShare=fitShare)
  File "/usr/local/lib/python3.6/site-packages/tpg/tpg_trainer.py", line 190, in select
    teamScoresMap[team][t] = team.outcomes[self.tasks[t]]
TypeError: 'set' object does not support indexing
```